#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: going live with 0% Experiment.
#
# Every stage ends in a value that lands in js/config.js. Nothing here needs a
# server: the site stays static, and Stripe, the form service and the mailing
# list provider each host their own half.
#
# Run it from anywhere:  bash tools/go-live.sh
# Stop any time with Ctrl-C; your answers are remembered for the next run.
# ──────────────────────────────────────────────────────────────────────────

# Everything below assumes the site root, whichever directory you started in.
cd "$(dirname "${BASH_SOURCE[0]}")/.." || exit 1

# Answers are kept here so a second run can offer them back as defaults. The
# real destination is js/config.js; this file is only a memo to itself.
ENV_FILE="tools/launch-answers.env"

TOTAL_STAGES=6

# set_config BLOCK.key VALUE [--raw] writes one value into js/config.js.
set_config() {
  if [[ "${3:-}" == "--raw" ]]; then
    node tools/set-config.mjs "$1" "$2" --raw
  else
    node tools/set-config.mjs "$1" "$2"
  fi
}

# ask_until KEY "Prompt" REGEX "complaint" keeps asking until the answer looks
# right. Everything captured here is written into js/config.js, so a typo or a
# stray Enter would otherwise end up on the live site quietly.
ask_until() {
  local key="$1" prompt="$2" pattern="$3" complaint="$4" value attempts=0
  while (( attempts < 5 )); do
    ask "$key" "$prompt"
    value="${!key}"
    if [[ -n "$value" && "$value" =~ $pattern ]]; then return 0; fi
    attempts=$((attempts + 1))
    warn "$complaint"
  done
  # Five misses in a row means nobody is typing — a closed stdin reads as an
  # endless stream of blanks, and spinning on that forever helps no one.
  printf '\n'
  warn "Giving up on this one. Re-run the wizard when you have the value."
  exit 1
}

banner "0% Experiment — going live"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "The price"
say "Stripe needs a number before it can make you a payment link, so this"
say "comes first. Until it is set, every buy button stays deliberately dead."
printf '\n'
step "Decide the price including VAT, the way a buyer will see it."
note "Belgian digital products are 21% VAT; Stripe Tax works it out for you."
printf '\n'

PRICE_CENTS=""
PRICE_TRIES=0
while [[ -z "$PRICE_CENTS" ]]; do
  if (( PRICE_TRIES >= 5 )); then
    printf '\n'
    warn "Giving up on the price. Re-run the wizard when you have decided."
    exit 1
  fi
  PRICE_TRIES=$((PRICE_TRIES + 1))
  ask PRICE_EUROS "Price in euros (e.g. 27 or 27,50):"
  PRICE_CENTS=$(node -e 'const n=Math.round(parseFloat(String(process.argv[1]).replace(",","."))*100);if(!Number.isFinite(n)||n<=0)process.exit(1);console.log(n)' "$PRICE_EUROS" 2>/dev/null) || {
    PRICE_CENTS=""
    warn "That is not a price. Try again, digits only."
  }
done

write_env PRICE_EUROS "$PRICE_EUROS"
set_config PRODUCT.priceCents "$PRICE_CENTS" --raw
set_config PRODUCT.priceConfirmed true --raw
pause "Done. Enter for the next stage."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Stripe: the product and the Payment Link"
say "Build this in TEST mode first. Payment links do not cross over, so you"
say "will make the live one at the end, once you have seen it work."
printf '\n'

ask_until SITE_DOMAIN "Your domain (e.g. www.0procentexperiment.be):" '^[A-Za-z0-9.-]+[.][A-Za-z]{2,}$' "Just the domain, no https:// and no trailing slash."
write_env SITE_DOMAIN "$SITE_DOMAIN"
set_config SITE.url "https://${SITE_DOMAIN}"
printf '\n'

say "Stripe Tax first, so EU VAT is charged correctly from the first sale:"
open_url "https://dashboard.stripe.com/settings/tax"
step "Set your origin address and register Belgium, then come back."
pause "Enter when Stripe Tax is set up."
printf '\n'

say "Now the payment link itself:"
open_url "https://dashboard.stripe.com/test/payment-links/create"
step "Add your product: name it, set the price you just chose, one-time payment."
step "Open the 'After the payment' section."
step "Under 'Confirmation page', choose to redirect customers to your website."
step "Paste this as the redirect URL — including the part in braces:"
printf '\n'
printf '    %s%shttps://%s/bevestiging.html?session_id={CHECKOUT_SESSION_ID}%s\n\n' \
  "$BOLD" "$GREEN" "$SITE_DOMAIN" "$RESET"
note "Stripe swaps {CHECKOUT_SESSION_ID} for the real id, and the confirmation"
note "page shows it as the order reference a buyer can quote in a mail."
printf '\n'
step "Create the link, then copy the https://buy.stripe.com/… URL."
printf '\n'

ask_until PAYMENT_LINK "Paste the Payment Link URL:" '^https://buy[.]stripe[.]com/' "A Stripe payment link starts with https://buy.stripe.com/"
write_env PAYMENT_LINK "$PAYMENT_LINK"
set_config PRODUCT.paymentLink "$PAYMENT_LINK"
printf '\n'
note "Test card 4242 4242 4242 4242, any future expiry, any CVC."
pause "Enter for the next stage."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Getting the workbook to the buyer"
warn "Stripe does not deliver files. It sends the receipt and the invoice;"
warn "handing over the PDF is yours to arrange. Three honest ways:"
printf '\n'
step "1. A fulfilment partner mails a unique link to whoever paid (gated)."
step "2. An unguessable URL on a private bucket, shown after checkout."
step "3. You mail it by hand, per sale."
printf '\n'
note "Only 1 keeps the file behind the payment. 2 means anyone given that URL"
note "can download it — fine for a cheap workbook, as long as you chose it."
printf '\n'

ask_until DELIVERY_CHOICE "Which one (1, 2 or 3)?" '^[123]$' "Answer 1, 2 or 3."
write_env DELIVERY_CHOICE "$DELIVERY_CHOICE"
printf '\n'

case "$DELIVERY_CHOICE" in
  2)
    say "Upload the PDF somewhere private under a long random filename."
    note "Cloudflare R2, Bunny and S3 all do this; avoid a guessable path."
    printf '\n'
    ask_until DELIVERY_URL "Paste the file URL:" '^https://' "That has to be a https:// URL."
    write_env DELIVERY_URL "$DELIVERY_URL"
    set_config DELIVERY.mode download
    set_config DELIVERY.url "$DELIVERY_URL"
    ;;
  1)
    say "Zapier is the quickest: trigger on Stripe's 'checkout.session.completed',"
    say "action sends an email with the download link to the customer's address."
    open_url "https://zapier.com/apps/stripe/integrations/email"
    step "Build the zap, send yourself a test, then come back."
    pause "Enter when the zap works."
    set_config DELIVERY.mode email
    SKIPPED+=("Check the fulfilment zap actually fires on a real sale")
    ;;
  *)
    say "By hand it is. Stripe mails you on every sale; you reply with the file."
    set_config DELIVERY.mode email
    SKIPPED+=("Automate delivery before this stops being fun (see README §2)")
    ;;
esac
pause "Enter for the next stage."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "The contact form"
say "A static page cannot send mail, so the form posts to a form service."
say "Formspree, Basin and Formspark all take exactly what the form sends."
printf '\n'
open_url "https://formspree.io/forms"
step "New form → point it at your own inbox → confirm the verification mail."
step "Turn its spam filter on; the form already carries a honeypot field."
step "Copy the endpoint: https://formspree.io/f/xxxxxxx"
printf '\n'

ask_until CONTACT_ENDPOINT "Paste the contact endpoint:" '^https://' "That has to be the https:// endpoint the service gave you."
write_env CONTACT_ENDPOINT "$CONTACT_ENDPOINT"
set_config ENDPOINTS.contact "$CONTACT_ENDPOINT"
pause "Enter for the next stage."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "The newsletter"
say "Mailing-list providers split into two camps, and yours decides how the"
say "page has to talk to it."
printf '\n'
step "1. Kit (ConvertKit)      — direct, the page can report real errors"
step "2. Formspree or Basin    — direct, same as the contact form"
step "3. Brevo                 — hidden-iframe post, no error reporting"
step "4. Mailchimp             — hidden-iframe post, no error reporting"
printf '\n'

ask_until NEWSLETTER_PROVIDER "Which one (1-4)?" '^[1-4]$' "Answer 1, 2, 3 or 4."
write_env NEWSLETTER_PROVIDER "$NEWSLETTER_PROVIDER"
printf '\n'

case "$NEWSLETTER_PROVIDER" in
  1) NL_MODE="json"; NL_FIELD="email_address"
     say "Kit → your form → Embed → HTML. The form's action is the endpoint,"
     say "and it looks like https://app.kit.com/forms/<id>/subscriptions"
     open_url "https://app.kit.com/forms" ;;
  2) NL_MODE="json"; NL_FIELD="email"
     say "Make a second form, exactly like the contact one, and copy its endpoint."
     open_url "https://formspree.io/forms" ;;
  3) NL_MODE="form"; NL_FIELD="EMAIL"
     say "Brevo → Contacts → Forms → your form → Share → the HTML embed. The"
     say "form's action is the endpoint, on sibforms.com."
     open_url "https://app.brevo.com/contact/list-listing" ;;
  *) NL_MODE="form"; NL_FIELD="EMAIL"
     say "Mailchimp → Audience → Signup forms → Embedded form. The form's"
     say "action is the endpoint, on list-manage.com."
     open_url "https://admin.mailchimp.com/lists/" ;;
esac
printf '\n'
warn "Turn on DOUBLE OPT-IN in that provider's settings before you collect a"
warn "single address. Belgium is in the EU and the confirmation mail is what"
warn "makes the consent provable. The site already promises people that mail."
printf '\n'

ask_until NEWSLETTER_ENDPOINT "Paste the newsletter endpoint:" '^https://' "That has to be the https:// action URL from the embed code."
write_env NEWSLETTER_ENDPOINT "$NEWSLETTER_ENDPOINT"
set_config ENDPOINTS.newsletter "$NEWSLETTER_ENDPOINT"
set_config NEWSLETTER.mode "$NL_MODE"
set_config NEWSLETTER.emailField "$NL_FIELD"
printf '\n'

if [[ "$NL_MODE" == "form" ]]; then
  note "That embed carries extra hidden inputs — Mailchimp's anti-bot b_xxx_yyy,"
  note "Brevo's locale. Copy them across or the provider may reject the signup."
  note "Format: name=value, comma separated. Leave empty if there are none."
  ask NEWSLETTER_HIDDEN "Hidden fields:"
  write_env NEWSLETTER_HIDDEN "$NEWSLETTER_HIDDEN"
  HIDDEN_LITERAL=$(node -e 'const s=(process.argv[1]||"").trim();const parts=s?s.split(",").map(p=>{const i=p.indexOf("=");const k=(i<0?p:p.slice(0,i)).trim();const v=(i<0?"":p.slice(i+1)).trim();return k?`${k}: ${JSON.stringify(v)}`:""}).filter(Boolean):[];console.log(parts.length?`{ ${parts.join(", ")} }`:"{}")' "$NEWSLETTER_HIDDEN")
  set_config NEWSLETTER.hiddenFields "$HIDDEN_LITERAL" --raw
fi
pause "Enter for the last stage."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Switch the demo off and check it"
say "Demo mode is the safety net for an unconfigured site: buy buttons walk to"
say "the confirmation page under a 'Demo' panel instead of charging anyone."
say "With a real payment link it steps aside on its own, but on a live site it"
say "should be off, so a misconfiguration fails loudly instead of quietly."
printf '\n'

if confirm "Turn demo mode off?"; then
  set_config DEMO.enabled false --raw
else
  note "Left on. Flip DEMO.enabled in js/config.js when you are ready."
fi
printf '\n'

say "Now walk it yourself, in this order:"
step "Buy the workbook with test card 4242 4242 4242 4242."
step "Check you land on bevestiging.html with an order reference."
step "Check the workbook actually reaches a buyer, however you chose to send it."
step "Send yourself a contact message and a newsletter signup."
step "Confirm the double opt-in mail arrives."
printf '\n'
warn "Then redo stage 2 in LIVE mode — the test payment link only spends fake"
warn "money — and paste the live URL over PRODUCT.paymentLink."
printf '\n'

SKIPPED+=("Swap in the LIVE Stripe payment link before announcing anything")
SKIPPED+=("SITE.company name/address/VAT in js/config.js — the legal pages show them")
SKIPPED+=("Have a lawyer read the three legal pages; they are drafts and say so")
SKIPPED+=("Update the canonical + og:url tags, sitemap.xml and robots.txt for your domain")

finish
